### ISSUE TITLE
createNameContract has no solution_provider_id

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfchain_client_js#21]
https://github.com/threefoldtech/tfchain_client_js/blob/a9ba36149564f1d3f58a441e9aea27b208f19767/lib/contract.js#L18-L19

- Cannot pass `solution_provider_id` to createNameContract function
- It takes `name` only

![photo_2022-08-21_16-35-42](https://user-images.githubusercontent.com/47260239/185796375-924a5079-5b64-4ebc-8e40-0a721de74d47.jpg)

**Comment by DylanVerstraete** [comment]
Fixed in 1.16.3
