### ISSUE TITLE
Add third party billing support

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_client_js#27]
- Extrinsics
- Getters

**Comment by DylanVerstraete** [comment]
https://github.com/threefoldtech/tfchain_client_js/commit/08b47643fe04e02c47e55afc1a132086a0ca27aa

**Comment by A-Harby** [comment]
![image](https://user-images.githubusercontent.com/109473873/214639457-dd2c2d57-5c04-40cb-8f82-eebf6291aa1b.png)
As explained in the two comments below all the functions above have been verified.
https://github.com/threefoldtech/tfchain/issues/445#issuecomment-1403963829
https://github.com/threefoldtech/tfchain/issues/562#issuecomment-1403925274
