### ISSUE TITLE
Implement new twin type

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_client_js#28]

**Comment by A-Harby** [comment]
Shouldn't creating twin in docs be updated to relay and pk?
![image](https://user-images.githubusercontent.com/109473873/218772744-6cd34678-b443-4962-a696-ccee15cb84a1.png)

**Comment by DylanVerstraete** [comment]
updated readme in: https://github.com/threefoldtech/tfchain_client_js/commit/305c0fad55cc6d2ed398580e6ea3110b579c79a9

**Comment by A-Harby** [comment]
Verified 
twin updated same as docs
![image](https://user-images.githubusercontent.com/109473873/220122505-35b03cc4-48ed-4268-a922-f9c14c0aa90c.png)
